version: "1"
services:
  nginx-server:
    build: ./nginx-server
    volumes:
      - photo-volume:${APPPATH}/${PHOTOS_DIR}
    ports:
      - "8080:80"
    depends_on:
      - node-server

  node-server:
    build:
      context: ./node-server
      args:
        APPPATH: ${APPPATH}
    environment:
      PHOTOS_DIR: ${PHOTOS_DIR}
    volumes:
      - photo-volume:${APPPATH}/${PHOTOS_DIR}

volumes:
  photo-volume:
